---
galaxy_info:
  role_name: supertokens
  author: Jarmatys
  description: SuperTokens Core authentication server container deployment
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - supertokens
    - auth
    - authentication
    - docker

dependencies: []
