---
caddy_enabled: false
caddy_container_name: caddy
caddy_image: caddy:2-alpine
caddy_image_cloudflare: ghcr.io/caddybuilds/caddy-cloudflare:latest
caddy_use_cloudflare: false
caddy_restart_policy: always

caddy_network: app-network

caddy_config_path: ""
caddy_cloudflare_token: ""

caddy_ports:
  - "80:80"
  - "443:443"

caddy_extra_env: {}
