---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  tags: fail2ban

- name: Configure fail2ban defaults
  ansible.builtin.template:
    src: fail2ban-jail.local.j2
    dest: /etc/fail2ban/jail.local
    backup: true
    mode: '0644'
  notify: restart fail2ban
  tags: fail2ban

- name: Ensure fail2ban service is enabled and running
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  tags: fail2ban

- name: Check fail2ban status
  ansible.builtin.command: fail2ban-client status
  register: fail2ban_status
  changed_when: false
  check_mode: false
  tags: fail2ban

- name: Display fail2ban status
  ansible.builtin.debug:
    var: fail2ban_status.stdout_lines
  tags: fail2ban
