---
- name: Install unattended-upgrades package
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  tags: updates

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    backup: true
    mode: '0644'
  tags: updates

- name: Configure automatic updates
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    backup: true
    mode: '0644'
  tags: updates

- name: Enable and start unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
  tags: updates
