---
mssql_enabled: false
mssql_container_name: mssql
mssql_image: mcr.microsoft.com/mssql/server:2019-latest
mssql_restart_policy: always

mssql_sa_password: "{{ mssql_sa_password }}"

mssql_data_dir: /opt/services/mssql/data
mssql_network: app-network

mssql_extra_networks: []

mssql_extra_env: {}

mssql_memory_limit: ""
mssql_memory_reservation: ""
mssql_cpus: ""
