---
galaxy_info:
  role_name: mssql
  author: Jarmatys
  description: Microsoft SQL Server container deployment
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - mssql
    - sqlserver
    - database
    - docker

dependencies: []
