---
galaxy_info:
  role_name: system_hardening
  author: Jarmatys
  description: System hardening for Ubuntu 22.04+ VPS servers
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - system
    - security
    - hardening
    - ubuntu
    - vps

dependencies: []
