---
seq_enabled: false
seq_container_name: seq
seq_image: datalust/seq:latest
seq_restart_policy: always

seq_network: app-network
seq_accept_eula: true
seq_first_run_no_auth: true

seq_extra_env: {}

seq_memory_limit: ""
seq_memory_reservation: ""
seq_cpus: ""
