---
galaxy_info:
  role_name: seq
  author: Jarmatys
  description: Seq logging server container deployment
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - seq
    - logging
    - docker

dependencies: []
