---
galaxy_info:
  role_name: rabbitmq
  author: Jarmatys
  description: RabbitMQ container deployment with management UI
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - rabbitmq
    - messaging
    - docker

dependencies: []
