---
portainer_enabled: false
portainer_container_name: portainer
portainer_image: portainer/portainer-ce:latest
portainer_restart_policy: always

portainer_network: app-network
portainer_vhost: ""

portainer_extra_env: {}

portainer_memory_limit: ""
portainer_memory_reservation: ""
portainer_cpus: ""
