---
galaxy_info:
  role_name: portainer
  author: Jarmatys
  description: Portainer CE container deployment for Docker management
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - portainer
    - docker
    - management

dependencies: []
