---
docker_version: ""
docker_compose_version: ""

docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
  default-ulimits:
    memlock:
      Hard: -1
      Name: "memlock"
      Soft: -1
    nofile:
      Hard: 65536
      Name: "nofile"
      Soft: 65536

docker_users:
  - "{{ vps_app_user }}"
docker_additional_users: []

docker_service_enabled: true
docker_service_state: started

docker_apt_repository: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - software-properties-common
  - python3-docker

docker_networks: []
docker_registries: []
