---
galaxy_info:
  role_name: typesense
  author: Jarmatys
  description: Typesense search engine container deployment
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - typesense
    - search
    - docker

dependencies: []
