---
rabbitmq_enabled: false
rabbitmq_container_name: rabbitmq
rabbitmq_image: rabbitmq:3-management
rabbitmq_restart_policy: always

rabbitmq_user: "{{ rabbitmq_user }}"
rabbitmq_password: "{{ rabbitmq_password }}"

rabbitmq_network: app-network
rabbitmq_extra_env: {}

rabbitmq_plugins: []

rabbitmq_config_path: ""

rabbitmq_memory_limit: ""
rabbitmq_memory_reservation: ""
rabbitmq_cpus: ""
